name: BFRffusion
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy
  - pip:
      - gradio
      - albumentations
      - opencv-contrib-python-headless
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning
      - omegaconf
      - test-tube>=0.7.5
      - streamlit>=1.12.1
      - einops>=0.3.0
      - transformers>=4.19.2
      - webdataset>=0.2.5
      - kornia>=0.6
      - open_clip_torch>=2.0.2
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas>=0.8.0
      - torchmetrics>=0.6.0
      - timm>=0.6.12
      - addict>=2.4.0
      - yapf>=0.32.0
      - prettytable>=3.6.0
      - safetensors>=0.2.7
      - basicsr>=1.4.2
      - lpips>=0.1.4
      - facexlib>=0.3.0
      - realesrgan>=0.3.0
